name: Build and Test
on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v1

      - name: vet
        run: make vet

      - name: fmt
        run: make fmt

      - name: lint
        run: |
          # temporary fix. See https://github.com/actions/setup-go/issues/14
          #export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/lint/golint
          make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test
